install.packages("stats")
install.packages("tidyverse")
install.packages("vegan")
install.packages("ggthemes")
install.packages("reshape2")
install.packages("devtools")
install.packages("viridis")
install.packages("knitr")
install.packages("gridExtra")
install.packages("BiocManager")
BiocManager::install("dada2", update=FALSE, ask=FALSE)
BiocManager::install("phyloseq", update=FALSE, ask=FALSE)
BiocManager::install("DECIPHER", update=FALSE, ask=FALSE)
BiocManager::install("phangorn", update=FALSE, ask=FALSE)
BiocManager::install("DESeq2", update=FALSE, ask=FALSE)
